titles= [
    "Acropole d'Athènes", "Agamemnon", "Agora", "Alexandre le Grand", "Amphore",
    "Antiquité grecque", "Apollon", "Arès", "Aristote", "Athéna", "Athènes",
    "Attique", "Byzance", "Byzantin", "Céramique grecque antique", "Chiton",
    "Clisthène", "Colonne grecque", "Corinthe", "Crète", "Cyclades", "Dédale",
    "Délos", "Delphes", "Démocratie athénienne", "Déméter", "Dionysos",
    "Ordre dorique", "Mer Égée", "Éleusis", "Épire", "Érechthéion", "Erinyes",
    "Eschyle", "Esclavage en Grèce antique", "Euripide", "Gorgone", "Grèce antique",
    "Gymnase (Antiquité)", "Hadès", "Héphaïstos", "Héra", "Héraclès", "Hermès",
    "Hérodote", "Hésiode", "Hoplite", "Iliade", "Ionie", "Isthme de Corinthe",
    "Kouros", "Laconie", "Laurion", "Lécythe", "Lycurgue", "Macédoine antique",
    "Méduse", "Métope", "Minos", "Minotaure", "Mosaïque romaine", "Musée de l'Acropole",
    "Mycènes", "Mystères d'Éleusis", "Nike (mythologie)", "Odéon", "Odyssée",
    "Mont Olympe", "Olympie", "Oracle de Delphes", "Orphée", "Pallas Athéna",
    "Panthéon (mythologie)", "Paphos", "Mont Parnasse", "Parthénon", "Péloponnèse",
    "Périclès", "Perséphone", "Phalange macédonienne", "Phidias", "Philippe II de Macédoine",
    "Philosophie grecque antique", "Pindare", "Platon", "Polis", "Poséidon",
    "Prométhée", "Propylées", "Pythie", "Jeux pythiques", "Rhétorique grecque",
    "Salamine (Grèce)", "Sappho", "Satyre", "Scylla", "Sparte", "Stade olympique",
    "Styx", "Symposium", "Thalassa", "Thalie", "Thèbes (Grèce)", "Thémistocle",
    "Théogonie", "Thésée", "Tirynthe", "Titan (mythologie)", "Trière", "Troie",
    "Typhon", "Vergina", "Xénophon", "Zeus", "Achéens", "Amphictionie",
    "Anastasis", "Archonte", "Arétè", "Bacchanales", "Boulè", "Chalcédoine",
    "Cithare", "Dème", "Drachme", "Écclésia", "Éphèbe", "Épicure", "Épopée",
    "Eunomie", "Géomorie", "Hécatombe", "Héliée", "Hiérophante", "Himation",
    "Kantharos", "Korè", "Krater", "Kryptie", "Labyrinthe", "Laurier (plante)",
    "Létè", "Métèque", "Nécropole", "Némée", "Néo-platonisme", "Obol (monnaie)",
    "Oikoumène", "Ostracon", "Paean", "Palladion", "Péplos", "Périèque",
    "Pétase", "Phratrie", "Pithos", "Pnyx", "Proxénie", "Psyche (mythologie)",
    "Sikinnis", "Skènè", "Stèle", "Stoa", "Télestèrion", "Thalassocratie",
    "Tragédie grecque", "Trésor de Delphes", "Tyrannie", "Xoanon", "Zénon de Kition",
    "Aegis", "Ananké", "Aréopage", "Asclépieion", "Autarkeia", "Bouleuterion",
    "Chresmologue", "Diadème", "Diaspora grecque", "Didrachme", "Dithyrambe",
    "Dokimasia", "Eleutheria", "Enkyklios paideia", "Ephébie", "Eschatologie grecque",
    "Eupatrides", "Genos", "Gerousia", "Hegemonia", "Herma", "Hexamilion",
    "Horos", "Hysplex", "Kerykeion", "Koine", "Kykeon", "Logographie",
    "Manteia", "Megalopolis (Grèce antique)", "Miasma", "Mimesis", "Mousike",
    "Nomisma", "Nomothète", "Oikos", "Omphalos", "Orchestra", "Paideia",
    "Panathénées", "Parodos", "Peplophore", "Peripetie", "Phylake", "Polemologie",
    "Prohedria", "Proskynesis", "Prytanée", "Sema", "Soteria", "Sphragis",
    "Strategos", "Syntrierarchie", "Tetradrachme", "Thesmophories", "Thetes",
    "Time", "Trapezitai", "Trittye", "Xenia", "Agoranome", "Aischrologia",
    "Anakalypsis", "Anthestéries", "Apatouries", "Archégète", "Arrhephorie",
    "Asebie", "Astu", "Atimie", "Aulos", "Bakis", "Bématiste", "Chresmographe",
    "Chryselephantin", "Daktylos", "Demiurge", "Dikè", "Dromos", "Eisphora",
    "Ekphora", "Emporion", "Endeixis", "Epibate", "Epigone", "Epikleros",
    "Eschara", "Exegete", "Geras", "Hagnète", "Hekatostylon", "Héraut",
    "Hiera", "Hierodule", "Hiketeia", "Hipparchie", "Homère", "Hydrie",
    "Hymette", "Hypogée", "Iambique", "Ichthyophage", "Kalliste", "Karyatide",
    "Katabasis", "Kernos", "Klepsydre", "Korybante", "Kylix", "Lénée",
    "Lesché", "Lithobole", "Logiste", "Machaon", "Mantique", "Métrologie antique",
    "Mystagogue", "Naos", "Nauarchie", "Neocore", "Oenochoe", "Oikiste",
    "Onomatothète", "Orgeones", "Palaistra", "Panhellénique", "Paraclausithyron",
    "Pédagogue", "Peitho", "Période (histoire grecque)", "Phiale", "Phylarque",
    "Pinax", "Pompé", "Proedros", "Prophasis", "Psephisma", "Pyrée",
    "Sarcophage", "Séisme", "Sémeion", "Skaphephorie", "Skolion", "Sotériologie",
    "Sphragistique", "Symmachie", "Syntaxis", "Syssitie", "Temenos", "Thalamege",
    "Thesmothète", "Thiasote", "Thorakite", "Thronosis", "Toxotès", "Trapeza",
    "Triérarque", "Tritogénie", "Trophonios", "Zoster", "Achéron", "Aède",
    "Aèthale", "Agoranome", "Aidos", "Akousmata", "Alastor", "Amphidromie",
    "Anarrhysis", "Anodos", "Aporrhèta", "Arété", "Arrhéphore", "Asbolie",
    "Ate", "Autochtonie", "Bacchante", "Catagogie", "Chthonien", "Daimon",
    "Diasie", "Dikastère", "Dromenon", "Eiresione", "Eisiterie", "Eleusinien",
    "Empousa", "Enagismos", "Endyma", "Enthousiasme", "Epiclère", "Epulie",
    "Eupatride", "Genos", "Hécate", "Hégémon", "Hétairie", "Hiéroscopie",
    "Horkos", "Hyménée", "Kantharos", "Katharsis", "Keryx", "Kléros",
    "Kourotrophos", "Krypteia", "Lithobole", "Makar", "Ménade", "Métis",
    "Mimésis", "Nao", "Nomos", "Obol", "Orchéstra", "Palladion", "Phratrie",
    "Skolie", "Stélé", "Télestérion", "Thiasos", "Toxotis", "Triobole",
    "Zagreus", "Aition", "Akroterion", "Ananke", "Areopage", "Asclépieion",
    "Autarkeia", "Bouleuterion", "Chresmologue", "Diadème", "Diaspora",
    "Didrachme", "Dithyrambe", "Dokimasia", "Eiresione", "Eleutheria",
    "Enkyklios", "Ephebeia", "Eschatologie", "Eupatrides", "Exegesis",
    "Géras", "Hagnète", "Hekatostylon", "Herma", "Hexamilion", "Horos",
    "Hysplex", "Iatromantis", "Kerykeion", "Kithariste", "Koine", "Kourotrophos",
    "Kykeon", "Logographie", "Manteia", "Megalopolis", "Miasma", "Mimesis",
    "Mousike", "Nomisma", "Nomothète", "Oikos", "Omphalos", "Orchéstra",
    "Orthographie", "Paideia", "Panathénées", "Parodos", "Peplophore",
    "Peripetie", "Phylake", "Polemologie", "Prohedria", "Proskynesis",
    "Prytanée", "Sema", "Soteria", "Sphragis", "Strategos", "Syntrierarchie",
    "Technites", "Tetradrachme", "Thesmophories", "Thetes", "Time", "Trapezitai",
    "Triakontoroi", "Trittye", "Xenia", "Agoranome", "Aischrologia", "Anakalypsis",
    "Anthestérie", "Apatourie", "Aporrheta", "Archégète", "Arrhephorie",
    "Asebie", "Astu", "Atimie", "Aulos", "Bakis", "Bateleur", "Bématiste",
    "Bouleutique", "Chresmographe", "Chryselephantin", "Daktylos", "Demiurge",
    "Dikè", "Dithyrambique", "Dromos", "Eisphora", "Ekphora", "Emporion",
    "Endeixis", "Ephebeia", "Epibate", "Epigone", "Epikleros", "Epulide",
    "Eschara", "Eunostide", "Exegete", "Geras", "Hagnète", "Hekatostylon",
    "Héraut", "Hiera", "Hierodule", "Hiketeia", "Hipparchie", "Homère",
    "Hydrie", "Hymette", "Hypogée", "Iambique", "Ichthyophage", "Kalliste",
    "Karyatide", "Katabasis", "Kernos", "Klepsydre", "Korybante", "Kourotrophe",
    "Kylix", "Lénée", "Léonte", "Lesché", "Lithobole", "Logiste", "Machaon",
    "Mantique", "Métrologie", "Mna", "Mystagogue", "Naos", "Nauarchie",
    "Neocore", "Nike", "Oenochoe", "Oikiste", "Oinochoé", "Onomatothète",
    "Orgeones", "Palaistra", "Palladium", "Panhellénique", "Paraclausithyron",
    "Pédagogue", "Peitho", "Péan", "Période", "Phiale", "Phratrie", "Phylarque",
    "Pinax", "Plebous", "Pompé", "Proedros", "Prophasis", "Proxène", "Psephisma",
    "Pyrée", "Sarcophage", "Séisme", "Séma", "Sémeion", "Sikinnis", "Skaphephorie",
    "Skolion", "Sotériologie", "Sphragistique", "Stratège", "Symmachie",
    "Syntaxis", "Syssitie", "Temenos", "Thalamege", "Thesmothète", "Thiasote",
    "Thorakite", "Thronosis", "Toxotès", "Trapeza", "Triérarque", "Tritogénie",
    "Trophonios", "Xérophtalmie", "Zoster"
]
