ext_1 = [
    "France", "Paris", "Lyon", "Berlin", "Londres", "New York", "Tokyo",
    "Internet", "Python", "Java", "Informatique", "Mathématiques", "Physique",
    "Chimie", "Biologie", "Histoire", "Géographie", "Philosophie", "Musique",
    "Peinture", "Sculpture", "Cinéma", "Théâtre", "Football", "Rugby", "Tennis",
    "Jeux olympiques", "Coupe du monde", "Tour Eiffel", "Louvre", "Notre-Dame",
    "Big Ben", "Statue de la Liberté", "Empire State Building", "Pyramides",
    "Colisée", "Parthénon", "Mona Lisa", "Van Gogh", "Picasso", "Dali", "Einstein",
    "Newton", "Darwin", "Galilée", "Copernic", "Marie Curie", "Pasteur", "Tesla",
    "Edison", "Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos", "Elon Musk",
    "Amazon", "Google", "Apple", "Microsoft", "Facebook", "Twitter", "Instagram",
    "YouTube", "Wikipedia", "Linux", "Android", "iOS", "Windows", "MacOS",
    "PlayStation", "Xbox", "Nintendo", "iPhone", "Samsung", "Sony", "Toyota",
    "Volkswagen", "Mercedes", "Ferrari", "Porsche", "Airbus", "Boeing", "NASA",
    "ESA", "Fusée", "Satellite", "Lune", "Mars", "Jupiter", "Saturne", "Voie lactée",
    "Galaxie", "Trou noir", "Big Bang", "Relativité", "Quantique", "ADN", "Génome",
    "Évolution", "Écologie", "Environnement", "Climat", "Réchauffement", "Pollution",
    "Renouvelable", "Solaire", "Éolien", "Nucléaire", "Pétrole", "Gaz", "Charbon",
    "Vélo", "Avion", "Train", "Voiture", "Bateau", "Sous-marin", "Fusée", "Drone",
    "Robot", "Intelligence artificielle", "Machine learning", "Blockchain", "Bitcoin",
    "Cryptomonnaie", "Réalité virtuelle", "Réalité augmentée", "Métaverse", "5G",
    "Internet des objets", "Cloud", "Big data", "Cybersécurité", "Hacking", "Virus",
    "Antivirus", "Firewall", "VPN", "Dark web", "Deep web", "BitTorrent", "Streaming",
    "Spotify", "Netflix", "Disney+", "Amazon Prime", "HBO", "YouTube Premium", "Deezer",
    "Apple Music", "Tidal", "SoundCloud", "Twitch", "Discord", "Zoom", "Skype",
    "WhatsApp", "Telegram", "Signal", "Messenger", "iMessage", "Slack", "Trello",
    "Notion", "Evernote", "OneNote", "Google Drive", "Dropbox", "iCloud", "Mega",
    "PayPal", "Visa", "Mastercard", "American Express", "Bitcoin", "Ethereum",
    "Dogecoin", "NFT", "OpenSea", "Binance", "Coinbase", "Kraken", "FTX", "Celsius",
    "Ledger", "Trezor", "Metamask", "Uniswap", "Aave", "Compound", "MakerDAO",
    "Cardano", "Solana", "Polkadot", "Avalanche", "Polygon", "Cosmos", "Algorand",
    "Tezos", "Chainlink", "Filecoin", "Arweave", "Helium", "Decentraland", "Sandbox",
    "Axie Infinity", "StepN", "Gods Unchained", "Magic Eden", "LooksRare", "SuperRare",
    "Foundation", "Rarible", "Zora", "Mirror", "Audius", "Arpeggi", "SoundXYZ",
    "Catalog", "Nina", "Mint Songs", "SoundMint", "PixelMap", "OnChainMonkey",
    "CryptoPunks", "Bored Ape", "Azuki", "Doodles", "Cool Cats", "World of Women"
]

ext_2 = [
    "Égypte antique", "Mésopotamie", "Grèce antique", "Rome antique", "Moyen Âge",
    "Renaissance", "Révolution française", "Napoléon", "Guerre mondiale", "Colonialisme",
    "Victor Hugo", "Molière", "Balzac", "Proust", "Camus", "Flaubert", "Zola",
    "Baudelaire", "Rimbaud", "Verlaine", "Surréalisme", "Goncourt", "Nobel littérature",
    "Baguette", "Croissant", "Fromage", "Vin", "Champagne", "Bordeaux", "Bourgogne",
    "Gastronomie française", "Michelin", "Bocuse", "Sushi", "Pizza", "Pasta", "Tapas",
    "Sociologie", "Anthropologie", "Psychanalyse", "Freud", "Jung", "Marx", "Keynes",
    "Platon", "Aristote", "Descartes", "Kant", "Nietzsche", "Sartre", "Structuralisme",
    "Himalaya", "Amazonie", "Sahara", "Antarctique", "Grand Canyon", "Barrière de corail",
    "Volcan", "Tsunami", "Ouragan", "Aurore boréale", "Écosystème", "Biodiversité",
    "Opéra Garnier", "Château de Versailles", "Cathédrale Notre-Dame", "Sagrada Familia",
    "Guggenheim", "Street art", "Graffiti", "Photographie", "Leica", "Impressionnisme",
    "Mozart", "Beethoven", "Chopin", "Bach", "Vivaldi", "Opéra", "Symphonie", "Philharmonie",
    "Stradivarius", "Piano", "Violon", "Callas", "Karajan",
    "Neuroscience", "Pandémie", "Vaccin", "Pasteur", "Fleming", "ADN", "CRISPR",
    "Téléscope Hubble", "LHC", "ISS", "Robotique", "Nanotechnologie",
    "Bouddhisme", "Christianisme", "Islam", "Judaïsme", "Hindouisme", "Sikhisme",
    "Athéisme", "Existentialisme", "Stoïcisme", "Confucius", "Taoïsme",
    "Panda géant", "Tigre du Bengale", "Éléphant d'Afrique", "Gorille", "Orang-outan",
    "Grand requin blanc", "Aigle royal", "Colibri", "Séquoia", "Orchidée", "Bonsaï",
    "Imprimerie", "Boussole", "Penicilline", "Électricité", "Avion", "Téléphone",
    "Radio", "Télévision", "Internet", "GPS", "Blockchain",
    "Démocratie", "Totalitarisme", "Guerre froide", "Mondialisation", "Écologisme",
    "Féminisme", "Droits de l'homme", "ONU", "Union européenne", "OTAN",
    "Escalade", "Parcours", "Plongée", "Voile", "Équitation", "Escrime", "Judo",
    "Taekwondo", "Badminton", "Squash", "Curling", "Bobsleigh",
    "Alhambra", "Angkor Wat", "Machu Picchu", "Pétra", "Borobudur", "Taj Mahal",
    "Saint-Basile", "Tour de Pise", "Chichen Itza", "Statue du Christ Rédempteur",
    "Banksy", "Koons", "Hirst", "Basquiat", "Kusama", "Performance", "Installation",
    "Land art", "Art numérique", "Art conceptuel",
    "Français", "Latin", "Grec ancien", "Sanskrit", "Hiéroglyphe", "Cunéiforme",
    "Esperanto", "Créole", "Dialecte", "Patrimoine linguistique",
    "Zeus", "Odin", "Anubis", "Quetzalcoatl", "Amaterasu", "Thor", "Hercule",
    "Ulysse", "Méduse", "Minotaure"
]

ext_3 = ["League of Legends", "The Outer Worlds", "Astroneer", "Subnautica", "Fortnite",
         "Starfield", "Eve Online", "Valorant", "Ligue des champions", "UEFA", "Ligue Europa",
         "No Man's Sky", "Super Mario Galaxy", "Mario 3D Land", "Mario Kart 8","Pokémon",
         "Portals", "Astérix et Obélix", "Nike", "Adidas", "Bayern de Munich",
         "PSG", "OM", "OL", "Racing Club de Lens", "Manchester City", "Manchester United",
         "Liverpool", "Everton", "Nottingham Forest", "Real de Madrid", "FC Barcelone",
         "Liga", "Ligue 1", "Ligue 2", "Bundesliga", "Championnat d'Angleterre de football","Overcooked",
         "Subnautica 2", "Snapchat", "Instagram", "Tik Tok", "Telegram (application)", "Playstation",
         "Apex Legends", "Borderlands 3", "Sea of Thieves", "Facebook", "Youtube"]
ext_4 = [
    "Processeur", "Carte graphique", "SSD", "RAM", "Carte mère",
    "Alimentation", "Refroidissement", "Ventilateur", "Watercooling", "Thermopaste",
    "Clavier mécanique", "Souris gaming", "Écran 144Hz", "Casque audio", "Microphone",
    "Webcam", "Capture card", "Hub USB", "Disque dur", "NAS",
    "NVIDIA", "AMD", "Intel", "ASUS", "MSI",
    "Gigabyte", "Corsair", "Logitech", "Razer", "SteelSeries",
    "Samsung", "LG", "Sony", "Apple", "Dell",
    "HP", "Lenovo", "Acer", "HyperX", "Western Digital",
    "FPS", "RPG", "MMORPG", "Battle Royale", "Open World",
    "Roguelike", "Sandbox", "Esport", "Speedrun", "Modding",
    "Early Access", "DLC", "Crossplay", "Ray Tracing", "DLSS",
    "VR", "AR", "Cloud Gaming", "LAN Party", "Emulateur",
    "The Witcher", "Cyberpunk 2077", "Elden Ring", "Call of Duty", "Fortnite",
    "League of Legends", "Valorant", "GTA", "Minecraft", "Skyrim",
    "Dark Souls", "Zelda", "Pokémon", "Halo", "God of War",
    "Assassin’s Creed", "Final Fantasy", "Starfield", "Overwatch", "Counter-Strike",
    "Steam", "Epic Games", "Ubisoft Connect", "Xbox Game Pass", "PlayStation Plus",
    "GeForce Now", "Twitch", "Discord", "OBS Studio", "Unreal Engine",
    "Unity", "Blender", "Photoshop", "DaVinci Resolve", "Visual Studio",
    "GitHub", "Linux", "Windows", "MacOS", "Android"
    "Canapé", "Réfrigérateur", "Four", "Micro-ondes", "Lave-vaisselle",
    "Machine à café", "Bouilloire", "Grille-pain", "Casserole", "Poêle",
    "Assiette", "Verre", "Couvert", "Torchon", "Éponge",
    "Savon", "Shampoing", "Dentifrice", "Brosse à dents", "Déodorant",
    "Rasoir", "Crème hydratante", "Serviette", "Peigne", "Baignoire",
    "Voiture", "Bus", "Métro", "Vélo", "Trottinette",
    "Permis de conduire", "Essence", "Station-service", "Feu rouge", "Passage piéton",
    "Bureau", "Ordinateur portable", "Stylo", "Cahier", "Agenda",
    "Réunion", "Email", "Collegue", "Patron", "Stagiaire",
    "Super marché", "Caddie", "Ticket de caisse", "Carte bancaire", "Espèces",
    "Facture", "Soldes", "Promotion", "Livraison", "Colis",
    "Livre", "Journal", "Télévision", "Radio", "Cinéma",
    "Musée", "Parc", "Pique-nique", "Randonnée", "Voyage",
    "Médecin", "Pharmacie", "Aspirine", "Pansement", "Thermomètre",
    "Hôpital", "Ambulance", "Pompiers", "Police", "Urgence",
    "Famille", "Ami", "Voisin", "Collègue", "Petit ami",
    "Petite amie", "Mariage", "Anniversaire", "Fête", "Cadeau"
]

ext_5 = [
    "Ruisseau", "Étang", "Marais", "Falaise", "Dune",
    "Prairie", "Champ", "Forêt", "Jardin", "Potager",
    "Gel", "Rosée", "Brouillard", "Grêle", "Orage",
    "Arc-en-ciel", "Lever de soleil", "Couchant", "Clair de lune", "Éclipse",
    "Joie", "Tristesse", "Colère", "Sérénité", "Nostalgie",
    "Enthousiasme", "Mélancolie", "Indifférence", "Curiosité", "Stupeur",
    "Gratitude", "Jalousie", "Culpabilité", "Fierté", "Embarras",
    "Optimisme", "Pessimisme", "Confusion", "Détermination", "Fatigue",
    "Apiculteur", "Boulanger", "Couturier", "Déménageur", "Ébéniste",
    "Fleuriste", "Géologue", "Horloger", "Infirmier", "Jardinier",
    "Kinésithérapeute", "Libraire", "Menuisier", "Notaire", "Opticien",
    "Plombier", "Quincaillier", "Restauration", "Serrurier", "Traducteur",
    "Bougie", "Clé USB", "Drap", "Épingle", "Fenêtre",
    "Gant", "Horloge", "Interrupteur", "Journal", "Lunettes",
    "Miroir", "Nappe", "Oreiller", "Parapluie", "Quenotte",
    "Rideau", "Savon", "Tiroir", "Vase", "Wattman",
    "Abricot", "Brocoli", "Câpre", "Datte", "Endive",
    "Figue", "Grenade", "Haricot", "Igname", "Jus",
    "Kiwi", "Lentille", "Mirabelle", "Noix", "Olive",
    "Poireau", "Quinoa", "Radis", "Sarrasin", "Topinambour",
    "Chuchoter", "Danser", "Écouter", "Fermer", "Guérir",
    "Habiller", "Imaginer", "Jongler", "Kiffer", "Lisser",
    "Murmurer", "Nager", "Observer", "Pousser", "Questionner",
    "Rire", "Sauter", "Toucher", "Urger", "Visser",
    "Atelier", "Bibliothèque", "Cave", "Douche", "Entrepôt",
    "Fabrique", "Grenier", "Hangar", "Igloo", "Juxtaposition",
    "Kiosque", "Laboratoire", "Magasin", "Nursery", "Observatoire",
    "Penderie", "Quai", "Réserve", "Salon", "Terrasse",
    "Anorak", "Baskets", "Chaussettes", "Denim", "Écharpe",
    "Foulard", "Gilet", "Hoodie", "Imperméable", "Jean",
    "Kilt", "Legging", "Manteau", "Noeud papillon", "Polo",
    "Robe", "Slip", "T-shirt", "Uniforme", "Veste"
]

ext_6 = [
    "Antinomie", "Béatitude", "Cohérence", "Dichotomie", "Équanimité",
    "Frugalité", "Gnose", "Harmonie", "Iconoclasme", "Jubilation",
    "Kairos", "Légitimité", "Métanoïa", "Nexus", "Omnipotence",
    "Paradoxe", "Quintessence", "Résilience", "Synchronicité", "Transcendance",
    "Abaque", "Bain-marie", "Chinois", "Décapsuleur", "Économe",
    "Fontaine à chocolat", "Grattoir", "Hachoir", "Inox", "Julienne",
    "Kougelhopf", "Louche", "Mandoline", "Napper", "Ouvre-huître",
    "Pilon", "Quenelle", "Râpe microplane", "Sauteuse", "Tamis",
    "Acupression", "Balnéothérapie", "Cryothérapie", "Drainage lymphatique", "Eutonie",
    "Fasciathérapie", "Gymnastique holistique", "Hypnothérapie", "Iridologie", "Jin Shin Jyutsu",
    "Kinésiologie", "Lithothérapie", "Moxibustion", "Naturopathie", "Ostéopathie",
    "Phytothérapie", "Qi Gong", "Réflexologie", "Shiatsu", "Tuina",
    "Alésoir", "Brûloir", "Ciseau à bois", "Défonceuse", "Étau limeur",
    "Filière", "Gouge", "Hotte aspirante", "Inciser", "Jauger",
    "Karcher", "Lime diamant", "Maillet", "Niveau laser", "Onduleur",
    "Pistolet à colle", "Quincaillerie", "Rabot électrique", "Scie sabre", "Tournevis dynamométrique",
    "Aquarelle", "Bodhran", "Calligramme", "Découpage", "Enluminure",
    "Fresque", "Gravure", "Haïku", "Improvisation", "Jazz manouche",
    "Kintsugi", "Linogravure", "Mosaïque", "Néons", "Origami",
    "Pochoir", "Quilling", "Raku", "Sfumato", "Tempera",
    "Bienveillance", "Altruisme", "Complicité", "Déférence", "Empathie",
    "Fiabilité", "Générosité", "Hospitalité", "Intégrité", "Jovialité",
    "Kinship", "Loyauté", "Médiation", "Négociation", "Ouverture d'esprit",
    "Pédagogie", "Quintessence", "Respect", "Solidarité", "Tolérance",
    "Chandelier", "Serpillière", "Passe-plat", "Couvre-lit", "Porte-manteau",
    "Bassinoire", "Bouillotte", "Chauffeuse", "Desserte", "Étagère à épices",
    "Fer à repasser", "Gril-pain", "Hotte", "Ionomètre", "Jacuzzi",
    "Lave-linge", "Miroir grossissant", "Napperon", "Ouvre-boîte", "Porte-parapluie",
    "Tourbière", "Estuaire", "Ravine", "Taïga", "Toundra",
    "Mousson", "Avalanche", "Éboulis", "Confluent", "Mangrove",
    "Polder", "Steppe", "Géyser", "Fjord", "Atoll",
    "Safran", "Giroflée", "Bruyère", "Mousse", "Lichen"
]

ext_7 = [
    "Aiguille", "Banc de sable", "Canyon", "Deltas", "Éboulis",
    "Fjord", "Gouffre", "Havre", "Inselberg", "Jardin botanique",
    "Karst", "Lagon", "Marais salant", "Névé", "Oasis",
    "Péninsule", "Quicksand", "Récif", "Stalactite", "Tourbière",
    "Uvala", "Volute", "Wadi", "Xérophyte", "Yak", "Zénith",
    "Atoll", "Brume", "Cirque", "Dune", "Estran",
    "Falaise", "Glacis", "Houle", "Isthme", "Jachère",
    "Kettle", "Limon", "Moraine", "Nuée", "Orage",
    "Précipice", "Queue de comète", "Roche mère", "Strate", "Tornade",
    "Upwelling", "Vallée", "Whitout", "Xylophage", "Yuzu",
    "Zéphyr", "Aurore", "Bise", "Cumulus", "Dérive",
    "Éclaircie", "Frimas", "Grêle", "Hiver", "Irisation",
    "Jaspe", "Khamsin", "Lueur", "Mousson", "Nacre",
    "Ondée", "Pruine", "Quasar", "Rosée", "Sirocco",
    "Tourbillon", "Ultraviolet", "Vent", "Willy-willy", "Xérès",
    "Algorithmie", "Biomimétisme", "Cryptographie", "Dendrochronologie", "Électrolyse",
    "Fractale", "Géothermie", "Hydrologie", "Informatique quantique", "Joule",
    "Kinétique", "Laser", "Météorite", "Nanotechnologie", "Ondes gravitationnelles",
    "Photovoltaïque", "Quantique", "Robotique", "Supraconductivité", "Téléportation",
    "Ultrason", "Vecteur", "Watt", "Xénon", "Yottabyte",
    "Zettaflop", "Astrophysique", "Bactériologie", "Chimie organique", "Dynamique",
    "Écologie", "Fusion", "Génome", "Hydraulique", "Isotope",
    "Jumeau numérique", "Kérosène", "Lévitation", "Mécanique", "Neuroscience",
    "Ozone", "Polymère", "Quark", "Rayon X", "Sismologie",
    "Thermodynamique", "Uranium", "Vortex", "Wi-Fi", "Xylème",
    "Yogourt", "Zygote", "Aérodynamique", "Biologie", "Cosmologie"
]

ext_8 = [
    "France", "Allemagne", "Italie", "Espagne", "Portugal",
    "Royaume-Uni", "Suisse", "Belgique", "Pays-Bas", "Suède",
    "Norvège", "Danemark", "Finlande", "Grèce", "Russie",
    "États-Unis", "Canada", "Mexique", "Brésil", "Argentine",
    "Chili", "Pérou", "Colombie", "Cuba", "Jamaïque",
    "Japon", "Chine", "Inde", "Corée du Sud", "Thaïlande",
    "Vietnam", "Indonésie", "Singapour", "Malaisie", "Arabie Saoudite",
    "Égypte", "Maroc", "Afrique du Sud", "Kenya", "Nigeria",
    "Tunisie", "Algérie", "Sénégal", "Ghana", "Éthiopie",
    "Australie", "Nouvelle-Zélande", "Fidji", "Samoa", "Tonga",
    "Paris", "Londres", "Rome", "Barcelone", "Berlin",
    "Amsterdam", "Vienne", "Prague", "Venise", "Athènes",
    "Moscou", "Istanbul", "Dublin", "Edimbourg", "Stockholm",
    "New York", "Los Angeles", "Miami", "Toronto", "Vancouver",
    "Mexico", "Rio de Janeiro", "Buenos Aires", "Lima", "Santiago",
    "Tokyo", "Pékin", "Shanghai", "Séoul", "Bangkok",
    "Singapour", "Dubai", "Hong Kong", "Delhi", "Mumbai",
    "Le Caire", "Casablanca", "Johannesburg", "Nairobi", "Tunis",
    "Marrakech", "Lagos", "Dakar", "Accra", "Addis-Abeba",
    "Sydney", "Melbourne", "Auckland", "Honolulu", "Suva",
    "Tour Eiffel", "Colisée", "Acropole", "Sagrada Familia",
    "Big Ben", "Tour de Pise ", "Château de Neuschwanstein",
    "Palais de Westminster ", "Atomium", "Pierre de Rosette",
    "Statue de la Liberté", "Christ Rédempteur", "Machu Picchu",
    "Chichén Itzá", "Capitole", "Empire State Building",
    "Golden Gate Bridge", "Maison Blanche", "Alamo",
    "Mont Rushmore",
    "Grande Muraille", "Taj Mahal", "Temples d'Angkor",
    "Pétra", "Opéra de Sydney", "Temple d'Or",
    "Burj Khalifa", "Pagode Shwedagon", "Hawa Mahal", "Fuji",
    "Pyramides de Gizeh", "Sphinx", "Mosquée Bleue",
    "Dôme du Rocher", "Mausolée de Mohammed V", "Koutoubia",
    "Grande Mosquée de Djenné", "Citadelle d'Alep", "Lalibela",
    "Mur des Lamentations", "Cité Interdite", "Hollywood Sign",
    "Crazy Horse Memorial", "Nelson's Column", "Manneken-Pis",
    "Napoléon Bonaparte", "Winston Churchill", "Abraham Lincoln", "Cléopâtre", "Charlemagne",
    "Charles de Gaulle", "Margaret Thatcher", "Nelson Mandela", "Mahatma Gandhi", "Justinien",
    "Albert Einstein", "Marie Curie", "Isaac Newton", "Galilée", "Stephen Hawking",
    "Thomas Edison", "Nikola Tesla", "Alan Turing", "Louis Pasteur", "Alexander Fleming",
    "Léonard de Vinci", "Michel-Ange", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí",
    "Frida Kahlo", "Claude Monet", "Andy Warhol", "Auguste Rodin", "Banksy",
    "William Shakespeare", "Victor Hugo", "J.K. Rowling", "George Orwell", "Ernest Hemingway",
    "Jane Austen", "Charles Dickens", "Molière", "Tolstoï", "Mark Twain",
    "Mozart", "Beethoven", "The Beatles", "Michael Jackson", "Elvis Presley",
    "Madonna", "Bob Marley", "Freddie Mercury", "David Bowie", "Édith Piaf",
    "Marilyn Monroe", "Charlie Chaplin", "Alfred Hitchcock", "Steven Spielberg", "Quentin Tarantino",
    "Meryl Streep", "Leonardo DiCaprio", "Audrey Hepburn", "Brad Pitt", "Angelina Jolie",
    "Elon Musk", "Steve Jobs", "Bill Gates", "Jeff Bezos", "Mark Zuckerberg",
    "Oprah Winfrey", "Malala Yousafzai", "Greta Thunberg", "Jack Ma", "Dwayne Johnson",
    "Pelé", "Mohamed Ali", "Michael Jordan", "Serena Williams", "Usain Bolt",
    "Lionel Messi", "Cristiano Ronaldo", "Roger Federer", "Tiger Woods", "Michael Phelps",
    "Walt Disney", "Stan Lee", "Bob Dylan", "Lady Gaga", "Beyoncé",
    "Taylor Swift", "Kanye West", "Kim Kardashian", "Ellen DeGeneres", "Gordon Ramsay",
    "Socrate", "Platon", "Aristote", "Descartes", "Nietzsche",
    "Voltaire", "Jean-Paul Sartre", "Confucius", "Bouddha", "Karl Marx"
]


#proportion doc scrappé : 75%
#print(len(ext_1)+ len(ext_2)+ len(ext_3)+len(ext_4)+ len(ext_5)+len(ext_6)+len(ext_7)+len(ext_8))